#%RAML 1.0
title: Challenge API
baseUri: http://local.inscale.com
/challenge:
  post:
    body: 
     application/json: 
      example: | 
        {
          "customerId": "123123123",
          "policyId": "7362786328732872"
        }
    responses: 
      200:
        body:
          application/json: 
            example: |
              {
                "status":"",
                "":""
               }
       