#%RAML 1.0
title: Challenge API
baseUri: http://local.inscale.com
/challenge:
  post:
    body: 
     application/json:
      schema: |   
            {
                "title": "challenge request",
                "type": "object",
                "properties": {
                  "customerId": {
                    "type": "string"
                  },
                  "policyId": {
                    "type": "string"
                  }
                 },
                "required": [ "customerId","policyId"]
              }
      example: | 
        {
          "customerId": "123123123",
          "policyId": "7362786328732872"
        }
    responses: 
      200:
        body:
          application/json: 
            example: |
              {
                "status": "1",
                "message": "Success"
              }
      400:
        body: 
          application/json: 
            example: |
              {
              }
      500:
        body: 
          application/json: 
            example: |
              {
                "errorDescription": "one or more dependancies are failed",
                "errors": [
                      {
                          "errorCode": "ERR500",
                          "errorMessage": "DocumentDistribution Service is down",
                          "systemID": "DOCUMENT_DISTRIBUTION"
                      }
                  ]
               }
      599:
        body: 
          application/json: 
            example: |
              {
                "errorDescription": "one or more dependancies are failed",
                "errors": [
                    {
                        "errorCode": "ERR599",
                        "errorMessage": "Customer Service not responsed within  time ",
                        "systemID": "CRM"
                    }
                ]
              }
      424:
        body: 
          application/json: 
            example: |
              {
                  "errorDescription": "one or more dependancies are failed",
                  "errors": [
                      {
                          "errorCode": "ERR599",
                          "errorMessage": "Customer Service not responsed within  time ",
                          "systemID": "CRM"
                      },
                      {
                          "errorCode": "ERR500",
                          "errorMessage": "Policy Service API is down at the moment ",
                          "systemID": "POLICY"
                      }
                  ]
              }
       
     
       